ERROR - 2025-06-20 08:33:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'ci4crm'@'localhost' to database 'ci4crm' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:202
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php(202): mysqli->real_connect('localhost', 'ci4crm', 'PdAADN6v/QZgwj_...', 'ci4crm', 3306, '', 0)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `product...', Array, false)
#4 C:\xampp\htdocs\CRM_CI4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CRM_CI4\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\CRM_CI4\app\Controllers\Ec.php(105): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\Ec->getProductDetail('7', 'tv')
#8 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ec))
#9 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `product...', Array, false)
#3 C:\xampp\htdocs\CRM_CI4\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CRM_CI4\system\BaseModel.php(717): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\CRM_CI4\app\Controllers\Ec.php(105): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\Ec->getProductDetail('7', 'tv')
#7 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ec))
#8 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-06-20 08:33:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'ci4crm'@'localhost' to database 'ci4crm' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:202
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php(202): mysqli->real_connect('localhost', 'ci4crm', 'PdAADN6v/QZgwj_...', 'ci4crm', 3306, '', 0)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `product...', Array, false)
#4 C:\xampp\htdocs\CRM_CI4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CRM_CI4\system\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CRM_CI4\app\Models\Product_model.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CRM_CI4\app\Controllers\Product.php(22): APP\Models\Product_model->getAllProductList()
#8 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\Product->fetchProductList()
#9 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Product))
#10 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT `product...', Array, false)
#3 C:\xampp\htdocs\CRM_CI4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CRM_CI4\system\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CRM_CI4\app\Models\Product_model.php(34): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CRM_CI4\app\Controllers\Product.php(22): APP\Models\Product_model->getAllProductList()
#7 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\Product->fetchProductList()
#8 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Product))
#9 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}
ERROR - 2025-06-20 08:33:19 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'ci4crm'@'localhost' to database 'ci4crm' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:202
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php(202): mysqli->real_connect('localhost', 'ci4crm', 'PdAADN6v/QZgwj_...', 'ci4crm', 3306, '', 0)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CRM_CI4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CRM_CI4\system\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CRM_CI4\app\Controllers\User.php(21): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\User->fetchUserList()
#8 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#9 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CRM_CI4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CRM_CI4\system\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CRM_CI4\app\Controllers\User.php(21): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\User->fetchUserList()
#7 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\User))
#8 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
ERROR - 2025-06-20 08:33:22 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'ci4crm'@'localhost' to database 'ci4crm' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:202
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php(202): mysqli->real_connect('localhost', 'ci4crm', 'PdAADN6v/QZgwj_...', 'ci4crm', 3306, '', 0)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\CRM_CI4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\CRM_CI4\system\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\CRM_CI4\app\Controllers\Ec.php(30): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\Ec->fetchCategoryList()
#8 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ec))
#9 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' to database '****' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\CRM_CI4\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\CRM_CI4\system\BaseModel.php(679): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\CRM_CI4\app\Controllers\Ec.php(30): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\Ec->fetchCategoryList()
#7 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ec))
#8 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2025-06-20 08:59:13 --> ParseError: syntax error, unexpected token "}", expecting "," or ";"
[Method: POST, Route: sales_order_submit]
in APPPATH\Controllers\Sales_order.php on line 64.
 1 SYSTEMPATH\Autoloader\Autoloader.php(295): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs\\CRM_CI4\\app\\Controllers\\Sales_order.php')
 2 SYSTEMPATH\Autoloader\Autoloader.php(271): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers\\Sales_order')
 3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers\\Sales_order')
 4 SYSTEMPATH\CodeIgniter.php(885): class_exists('\\App\\Controllers\\Sales_order', true)
 5 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->startController()
 6 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-20 08:59:30 --> Error: Cannot use object of type stdClass as array
[Method: POST, Route: sales_order_submit]
in APPPATH\Controllers\Sales_order.php on line 63.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Sales_order->sales_order_submit()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales_order))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-20 09:00:15 --> TypeError: json_decode(): Argument #1 ($json) must be of type string, array given
[Method: POST, Route: sales_order_submit]
in APPPATH\Controllers\Sales_order.php on line 60.
 1 APPPATH\Controllers\Sales_order.php(60): json_decode([...])
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Sales_order->sales_order_submit()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales_order))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2025-06-20 10:15:48 --> Error: Class "App\Models\Sales_order_detail_model" not found
[Method: POST, Route: sales_order_submit]
in APPPATH\Controllers\Sales_order.php on line 97.
 1 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Sales_order->sales_order_submit()
 2 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales_order))
 3 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2025-06-20 14:29:40 --> mysqli_sql_exception: Unknown column 'product_image' in 'field list' in C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php:327
Stack trace:
#0 C:\xampp\htdocs\CRM_CI4\system\Database\MySQLi\Connection.php(327): mysqli->query('UPDATE `sales_o...', 0)
#1 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `sales_o...')
#2 C:\xampp\htdocs\CRM_CI4\system\Database\BaseConnection.php(652): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `sales_o...')
#3 C:\xampp\htdocs\CRM_CI4\system\Database\BaseBuilder.php(2521): CodeIgniter\Database\BaseConnection->query('UPDATE `sales_o...', Array, false)
#4 C:\xampp\htdocs\CRM_CI4\app\Controllers\Sales_order.php(303): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(933): App\Controllers\Sales_order->sales_order_submit()
#6 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Sales_order))
#7 C:\xampp\htdocs\CRM_CI4\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\CRM_CI4\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\CRM_CI4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\CRM_CI4\public\index.php(59): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
